version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command: 
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=fedevlopez17@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  db:
    image: mysql:8.0
    container_name: ceramic-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ceramic_affair_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./ceramic_affair_web
    container_name: ceramic-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ceramic_affair_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_TO: ${MAIL_TO}

      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}

      JWT_SECRET: ${JWT_SECRET}

      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_WWW_URL: ${FRONTEND_WWW_URL}

    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ceramic-backend.rule=Host(`api.ceramic-affair.me`)"
      - "traefik.http.routers.ceramic-backend.entrypoints=websecure"
      - "traefik.http.routers.ceramic-backend.tls.certresolver=myresolver"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./ceramic-frontend
    container_name: ceramic-frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`ceramic-affair.me`) || Host(`www.ceramic-affair.me`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.service=ceramic-frontend"
      - "traefik.http.services.ceramic-frontend.loadbalancer.server.port=80"

volumes:
  mysql_data:
  uploads_data:
  letsencrypt:
